### ISSUE TITLE
Streaming API Broken after Model 3 updated to 2018.18.3 04dfd3c

### ISSUE THREAD

**Issue by seeARMS** [timdorr/tesla-api#68] opened 2018-05-21 00:22 UTC
### Expected behavior
The streaming API works as intended, and returns updates every ~250 msec.

### Actual behavior
The streaming API connects successfully, but does not return anything regardless of the state of the Model 3 (awake, driving, etc - nothing is returned).

### Steps to reproduce the behavior
This started as soon as my Model 3 updated to version 2018.18.3 04dfd3c. Streaming was working before that, then immediately after the update, it began returning nothing. I've restarted the car, restarted the server, tried across several different days, and the streaming API continues to return nothing.

**Comment by timdorr** [comment] 2018-05-21 00:30
Does the app work? If so, there may be a subtle API change we need to match. If not, then it's on Tesla's end. This repo isn't official support for the API in any way.

**Comment by seeARMS** [comment] 2018-05-21 00:37
The official Tesla app does work. All other REST API calls work too - just the streaming API does not. So I'm guessing it may be a subtle API change that we need to match, but I also haven't heard of anyone else encountering issues (but this Model 3 version is rather new, so perhaps it just has not reached enough people yet for anyone to notice).

**Comment by flexgames** [comment] 2018-05-21 20:29
FWIW I'm having the same issue with my Model 3. 

Joe

**Comment by flexgames** [comment] 2018-05-31 00:09
Curious if anyone has seen this besides @seeARMS and me? Not sure where to go to troubleshoot or fix this... Open to any ideas.

**Comment by kodek** [comment] 2018-05-31 00:17
I've also noticed this. I wrote an app to collect car metrics into InfluxDB, and I've had to stop collecting stream-based metrics for the Model 3. The Model S still works fine.

**Comment by seeARMS** [comment] 2018-05-31 04:52
Even after the latest Model 3 update (2018.18.13 6a8a06e, which I received today), streaming still does not work.

@timdorr, how did you originally find the streaming API URL and params? I'm happy to start investigating if I know where to start.

**Comment by flexgames** [comment] 2018-06-01 17:29
Out of frustration on this, I threw Charles Proxy on the iPhone today and then fired up the official Tesla app on the iPhone. I then let it stream the telemetry and noticed back in Charles that it never actually hits `streaming.vn.teslamotors.com` (and yet it streams). It does, however, hit `https://owner-api.teslamotors.com`. I'm no proxy expert but if these results are correct, maybe they're pulling the telemetry through owner-api now? I'd love for someone else to confirm my findings if you feel like trying....

**Comment by timdorr** [comment] 2018-06-01 18:21
Try going to the Location view (the one with the map) and seeing what it connects to. It might be all on the same endpoint now, given that doing WebSockets is more easy to do in modern versions of Rails and that is what this weekend's maintenance was for.

**Comment by flexgames** [comment] 2018-06-01 18:29
I did indeed switch over to the Location view, and the endpoint never changed. Though when I tried to have Charles capture the data between teslamotors.com and my phone, it never worked. But at least I could see the endpoint before I tried capturing.

**Comment by timdorr** [comment] 2018-06-01 18:45
It's over HTTPS and is certificate pinned, so I don't know if you can get it working. Possibly with a jailbroken phone? I'm not sure how that works in iOS-land.

I'll try it with my car some time soon and decompile the app to see if they reference a new endpoint somewhere.

**Comment by kodek** [comment] 2018-06-01 20:20
From the APK:

"STREAMING_SERVER_BASE_URL": "wss://streaming.vn.teslamotors.com/",

I'm assuming it was over http(s) before?

**Comment by timdorr** [comment] 2018-06-01 21:28
wss: is "WebSocket Secure", which is just HTTPS.

**Comment by kodek** [comment] 2018-06-01 21:53
Right, but was the constant prefixed with http(s) before?

**Comment by josebet1** [comment] 2018-06-15 02:48
Looked through the APK and it seems there's a new endpoint for location streaming:
`StreamingServerEndpoints={LOCATION_STREAMING:"streaming/",AUTOPARK_SUMMON:"connect/"}`

I have been trying to connect and subscribe to the data feed, but the server replied with vehicle disconnected even when the car was driving.
`{"msg_type":"data:error","tag":"${vehicle_id}","value":"disconnected","error_type":"vehicle_disconnected"}`

**Comment by flexgames** [comment] 2018-06-30 03:49
Per this 
[post](https://teslamotorsclub.com/tmc/posts/2834656/)

this member says it's working for his 3, albeit at a low frequency. For my part I haven't been able to confirm that. 

@jonasman did you have a chance to test it on your S?

**Comment by flexgames** [comment] 2018-06-30 06:57
I have confirmed that the curl command works, but doesn't continue streaming for long (in fact only returns one line)

`$ curl --user '<MY_EMAIL>:<TOKEN>' -i -N  --header "Sec-WebSocket-Key: SGVsbG8sIHevcmxkIQ==" -H "Sec-WebSocket-Version: 13" -H "Connection: Upgrade" -H "Upgrade: websocket" -H "Host: streaming.vn.teslamotors.com" -H "Origin: https://streaming.vn.teslamotors.com" https://streaming.vn.teslamotors.com/connect/<MY_VEHICLE_ID>`


returns

`HTTP/1.1 101 Switching Protocols
Server: nginx
Date: Sat, 30 Jun 2018 06:52:04 GMT
Connection: upgrade
Upgrade: websocket
Sec-WebSocket-Accept: 2iz1EJF5jgwwj5BWHJtNB3HEdhw=

�~�{"autopark":{"autopark_pause_timeout":2000,"autopark_stop_timeout":10000,"heartbeat_frequency":500},"connection_timeout":20000,"msg_type":"control:hello"}�9{"autopark_style":"dead_man","msg_type":"autopark:style"}�={"autopark_state":"unavailable","msg_type":"autopark:status"}�6{"homelink_nearby":false,"msg_type":"homelink:status"}�Q{"latitude":43.42311535,"longitude":-101.262218,"msg_type":"vehicle_data:location"}���������������������`

**Comment by jonasman** [comment] 2018-06-30 09:06
@flexgames i tried to open the http streaming (not websocket) to `owner-api.teslamotors.com` and i get error 404.
`streaming.vn.teslamotors.com` works fine and i get car events.

**Comment by abl** [comment] 2018-07-13 07:50
I haven't been able to get anything interesting from the `/streaming` endpoint yet on my Model 3.

The `/connect/<ID>` endpoint, if the car is awake, has some interesting properties. First, only one session can be connected at a time - otherwise you get `{'msg_type': 'control:goodbye', 'reason': 'vehicle_already_connected'}`.

Sending a `autopark:heartbeat_app` message at `heartbeat_frequency` yields a `heartbeat_car` message like: `{'msg_type': 'autopark:heartbeat_car', 'timestamp': 1531467022.817666}` and keeps the socket alive.

I get the following when connecting a session to my Model 3 LR (EAP, homelink not yet configured):

```
{'autopark': {'autopark_pause_timeout': 2000, 'autopark_stop_timeout': 10000, 'heartbeat_frequency': 500}, 'connection_timeout': 20000, 'msg_type': 'control:hello'}
{'autopark_style': 'standard', 'msg_type': 'autopark:style'}
{'autopark_state': 'ready', 'msg_type': 'autopark:status'}
{'homelink_nearby': False, 'msg_type': 'homelink:status'}
{'latitude': 47.60620, 'longitude': -122.332100, 'msg_type': 'vehicle_data:location'}
```

(Latitude and longitude anonymized.)

Trying to connect when my car is asleep:

```
{'autopark': {'autopark_pause_timeout': 2000, 'autopark_stop_timeout': 10000, 'heartbeat_frequency': 500}, 'connection_timeout': 20000, 'msg_type': 'control:hello'}
{'msg_type': 'control:goodbye', 'reason': 'vehicle_offline'}
```

Based on this and some other digging I'm pretty sure the `/connect/<ID>` endpoint will only be interesting to folks doing Summon calls.

**Comment by ddaddy** [comment] 2018-07-13 08:31
I've been playing with the new `streaming/` endpoint.
My 8 month old Model S works fine with both the old streaming endpoint and this new streaming endpoint. I can get updates 4x per second just like with the old streaming endpoint.

The strange thing with the new endpoint is i've had it confirmed with my same code that it doesn't work on Model 3, but also doesn't work on some newer Model S (Neither new or old endpoint works)!

It just returns `vehicle_disconnected`

I've looked through the app code and don't see anywhere it would do anything different for some cars over others so I really don't understand this response.

**Comment by ddaddy** [comment] 2018-07-13 08:42
Another strange thing. The `vehicle_disconnected` error is an error code for `AutoparkSummonErrorTypes` which is for the summon `/connect/` endpoint. So no idea what the app will do when getting that back from the `/streaming/` endpoint.

**Comment by davidhodge** [comment] 2018-08-12 01:03
After not getting data for a while, I'm now getting 401s at the old endpoint.

**Comment by flexgames** [comment] 2018-09-05 19:10
Is anyone getting any further? I'm only able to pull the lat/long, but not orientation, speed, etc. The lat/long I'm getting by constantly polling, but I'm missing the other features. What is frustrating is that the iPhone/Android apps obviously can pull that information, and are likely having the data streamed to them...

**Comment by flexgames** [comment] 2018-09-05 19:31
> Are you driving the car when streaming? If it's stationary, it doesn't give the other fields.

You're right about when it's stationary.

When driving I can *only* get the lat/long information (besides some other useless information):
`�9{"autopark_style":"dead_man","msg_type":"autopark:style"}�:{"autopark_state":"disabled","msg_type":"autopark:status"}�6{"homelink_nearby":false,"msg_type":"homelink:status"}Received 82 byte
�P{"latitude":44.17315,"longitude":-126.235282,"msg_type":"vehicle_data:location"}Received 2 byte
�Received 2 byte`

I'm doing a fair amount of parsing and clean up just to pull that data out and use in a map..

**Comment by timdorr** [comment] 2018-09-05 20:07
That's the AutoPark/Summon endpoint. The streaming API is separate and provides a CSV-like stream of data. `https://streaming.vn.teslamotors.com/stream/VEHICLE_ID`, not the `/connect/VEHICLE_ID` endpoint.

**Comment by josebet1** [comment] 2018-09-06 13:35
The Model 3 location streaming API has been 'broken' for a while. It seems that the location part of the iOS app, at least for the Model 3, is polling every ~5 seconds using the API

**Comment by flexgames** [comment] 2018-09-06 14:21
> The Model 3 location streaming API has been 'broken' for a while. It seems that the location part of the iOS app, at least for the Model 3, is polling every ~5 seconds using the API

What I can't figure out is how they're getting the orientation and speed if they're hitting the summon endpoint...  Unless they're using another endpoint.

**Comment by josebet1** [comment] 2018-09-06 14:26
I suppose they are getting it from `https://owner-api.teslamotors.com/api/1/vehicles/${vehicleId}/data` there is the `drive_state` key in the obj that includes heading and speed.

**Comment by mitchcapper** [comment] 2018-10-13 17:59
I noticed this issue and it sounds like some raw logs might be helpful.  I have sanitized most of the longer strings with 1234 but should provide the session info:

There are some native WS ping/pongs go throughout the session as well
```
GET https://streaming.vn.teslamotors.com/connect/12341234 HTTP/1.1
Cookie: _ga=GA1.2.12341234.12341234
origin: https://streaming.vn.teslamotors.com/
X-Tesla-User-Agent: TeslaApp/3.6.0-352/6e736b5a1/android/9
User-Agent: Mozilla/5.0 (Linux; Android 8; 12341234; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/12341234 Mobile Safari/537.36
Authorization: Basic 12341234==
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Key: 12341234==
Sec-WebSocket-Version: 13
Host: streaming.vn.teslamotors.com
Accept-Encoding: gzip

{"autopark":{"autopark_pause_timeout":2000,"autopark_stop_timeout":10000,"heartbeat_frequency":500},"connection_timeout":20000,"msg_type":"control:hello"}
{"timestamp":12341234,"msg_type":"control:ping"}
{"autopark_style":"dead_man","msg_type":"autopark:style"}
{"autopark_state":"ready","msg_type":"autopark:status"}
{"homelink_nearby":true,"msg_type":"homelink:status"}
{"latitude":12341234,"longitude":12341234,"msg_type":"vehicle_data:location"}
{"latitude":12341234,"longitude":12341234,"msg_type":"autopark:cmd_forward"}
{"cmd_type":"autopark:cmd_forward","msg_type":"autopark:cmd_result","reason":"","result":true}
{"timestamp":12341234,"msg_type":"autopark:heartbeat_app"}
{"autopark_state":"preparing","msg_type":"autopark:status"}
{"msg_type":"autopark:heartbeat_car","timestamp":12341234}
{"timestamp":12341234,"msg_type":"autopark:heartbeat_app"}
{"msg_type":"autopark:heartbeat_car","timestamp":12341234}
{"timestamp":12341234,"msg_type":"autopark:heartbeat_app"}
{"timestamp":12341234,"msg_type":"control:ping"}
{"autopark_state":"active_forward","msg_type":"autopark:status"}
{"msg_type":"control:pong","timestamp":12341234}
{"msg_type":"autopark:heartbeat_car","timestamp":12341234}
{"msg_type":"autopark:cmd_abort"}
{"cmd_type":"autopark:cmd_abort","msg_type":"autopark:cmd_result","reason":"","result":true}
```

**Comment by mir9** [comment] 2018-10-13 19:35
> The Model 3 location streaming API has been 'broken' for a while. It seems that the location part of the iOS app, at least for the Model 3, is polling every ~5 seconds using the API

For Tesla 3, The poll works for me only when the car is in PARKING.

When the car is moved, the `/data_request/drive_state` returns 

```
{"response":null,"error":"upstream internal error","error_description":""}
```

Any help on how can i read the `drive_state` while the car is moving?

**Comment by timdorr** [comment] 2018-12-11 20:16
So, the bigger issue here is that the streaming API is still undocumented. I'm going to close this issue out and open a new one to track that.

**Closed by timdorr** 2018-12-11 20:16 UTC
Labels: bug

**Comment by ddaddy** [comment] 2019-11-17 11:58
This is very odd, but I’ve just had it confirmed from a user of my app that it’s started working on Model 3. I’ve made no changes to my code yet data is now streaming. I don’t know what software version this started on. Can anyone else confirm the streaming API now works as it used to on newer vehicles?

**Comment by timdorr** [comment] 2019-11-17 17:26
Even if it does work, I wouldn't rely on it. They are clearly focused on WebSockets for anything bidi or streaming.

**Comment by dacastro4** [comment] 2020-02-26 21:26
Hey guys. Is the streaming API working?
I've been trying 
```
curl --user 'email:access_token' -i -N \
   --header "Sec-WebSocket-Key: SGVsbG8sIHevcmxkIQ==" \
   -H "Sec-WebSocket-Version: 13" \
   -H "Connection: Upgrade" \
   -H "Upgrade: websocket" \
   -H "Host: streaming.vn.teslamotors.com" \
   -H "Origin: https://streaming.vn.teslamotors.com" https://streaming.vn.teslamotors.com/connect/vehicle_id
```
and I keep getting
```HTTP/1.1 500 Internal Server Error
Server: nginx
Date: Wed, 26 Feb 2020 21:25:23 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 83
Connection: keep-alive
X-Content-Type-Options: nosniff

Got HTTP status: 404 Not Found for . Response: {"error":"vehicle not found (404)"}```

**Comment by Ahmadre** [comment] 2020-08-24 19:49
We got it working fluently guys 👍 

have a look here: https://github.com/TeslaToolkit/tesla.dart/blob/master/bin/summon.dart

**Comment by pmcanseco** [comment] 2020-08-29 20:06
I'm having identical symptoms to @dacastro4 . If anyone has managed to get it working I'd like to see what their `curl` call looks like.

**Comment by timdorr** [comment] 2020-08-30 17:47
The original streaming.vn server has been removed. I'm not sure if it still responds, but it no longer works. You need to use the WebSocket server now.

**Comment by pmcanseco** [comment] 2020-08-30 18:15
> You need to use the WebSocket server now.

I thought streaming.vn was the WS server, is there another WS server or mechanism via the owners-api.teslamotors.com endpoint?

**Comment by timdorr** [comment] 2020-08-31 20:25
Sorry, I meant specifically that the streaming.vn.teslamotors.com/stream/ _endpoint_ has been removed. The server is still there, just that endpoint is defunct.
