### ISSUE TITLE
 2021.36.5.5 set charging power

### ISSUE THREAD

**Issue by Urs-Eppenberger** [timdorr/tesla-api#467] opened 2021-10-30 18:39 UTC
I just upgraded my Tesla Model 3 with SW version 2021.36.5.5
The release note states, that there is now the possibility to configure the charging power via the Tesla App. I checked and this seems true. There is now a new configuration option in the iPhone Tesla App.

If the App can control charging power, then there is most probably another option available in the API.
Could you try to figure this out and update the API documentation?
I have no clue about how to attack this problem.

Kind regards,
Urs.

**Comment by timdorr** [comment] 2021-10-30 20:41
Duplicate of #445

**Closed by timdorr** 2021-10-30 20:41 UTC
