### ISSUE TITLE
Owners Api not working 

### ISSUE THREAD

**Issue by fkhera** [timdorr/tesla-api#239] opened 2020-10-25 02:09 UTC
When I call the owners api I am getting errors the errors seems to indicated the owners api library does not work anymore since they use a new authentication endpoint .

When I call for a token using the old api, i keep getting challenged with:
response:
{"response": "https://myt-websvc-vip1.tesla.com:443/teslamobileservices/users/authenticate_=>_authorization_required"}

Does this mean they stopped the old interface?

https://tesla-api.timdorr.com/api-basics/authentication

Can these steps still work"??
OST /oauth/token?grant_type=password
The initial authentication process is via an OAuth 2.0 Password Grant with the same credentials used for tesla.com and the mobile apps.
The current client ID and secret are available h

**Comment by timdorr** [comment] 2020-10-25 21:13
Duplicate of #215, most likely. Regardless, this isn't a support system for Tesla's API. There is no official support for it and no one here has any power to change or fix anything about it. We're at the whims of whatever Tesla decides to do.

**Closed by timdorr** 2020-10-25 21:13 UTC
